version: '3'

services:
    nms:
        image: bwdigital/nms:v1.0.0
        container_name: nms
        restart: unless-stopped
        networks:
            - preprod_network
        deploy:
            resources:
                limits:
                    memory: 2048M
        ports:
            - "9005:9005"
            - "5701:5701/udp"
        environment:
            - SPRING_PROFILES_ACTIVE=dev
        volumes:
            - '/docker-files/nms-volume/logs:/var/logs'

networks:
    preprod_network:
        external: true
