version: '3'

services:
    brokerai:
        image: bwdigital/brokerai:v1.0.0
        container_name: brokerai
        restart: unless-stopped
        networks:
            - prod_network
        expose:
            - "3100"
        volumes:
            - '/docker-files/brokerai-volume/logs:/var/logs'

networks:
    prod_network:
        external: true
