[SERVICE]
    Flush         1
    Log_Level     info
    Parsers_File  parsers.conf

[INPUT]
    Name              tail
    Path              /var/lib/docker/containers/*/*-json.log
    Parser            docker
    Tag               docker.*
    Mem_Buf_Limit     50MB
    Skip_Long_Lines   On
    Refresh_Interval  5
    Docker_Mode       On
    Path_Key          path

[FILTER]
    Name    parser
    Match   docker.*
    Key_Name path
    Parser  container_path
    Reserve_Data True

[FILTER]
    Name   lua
    Match  docker.*
    script container_map.lua
    call   map_container_name

[FILTER]
    Name    lua
    Match   docker.*
    script  strip_ansi.lua
    call    process

[FILTER]
    Name   modify
    Match  docker.*
    Add    job docker

[OUTPUT]
    Name   loki
    Match  docker.*
    Host   10.10.1.4
    Port   3101
    Labels job=docker
    Line_Format json
