[PARSER]
    Name        docker
    Format      json
    Time_Key    time
    Time_Format %Y-%m-%dT%H:%M:%S.%L
    Time_Keep On

[PARSER]
    Name container_path
    Format regex
    Regex ^/var/lib/docker/containers/(?<container_id>[a-f0-9]+)/.*\.log$
