#############################################################################################################
#
# expected folders: B1,T2,T3,T4,T50,T51,T52
#
#############################################################################################################
# NZMA_A 172.29.134.30 	00:15:00	B1
# 			00:30:00	T2
# 			00:45:00	T3
# 			01:00:00	T4
# 			01:15:00	T50
# 		 	01:30:00	T51
# 	 		01:45:00	T52
# NZMA_B 172.29.134.31	12:15:00	B1
# 	 		12:30:00	T2
# 	 		12:45:00	T3
# 	 		13:00:00	T4
# 		 	13:15:00	T50
# 	 		13:30:00	T51
# 	 		13:45:00	T52
# NZHQ	 172.29.136.30	04:15:00	B1
# 		 	04:30:00	T2
# 	 		04:45:00	T3
# 	 		05:00:00	T4
# 	 		05:15:00	T50
# 	 		05:30:00	T51
# 	 		05:45:00	T52
# HIKA_A 172.29.132.30	02:15:00	B1
# 	 		02:30:00	T2
# 	 		02:45:00	T3
# 	 		03:00:00	T4
# 	 		03:15:00	T50
# 	 		03:30:00	T51
# 	 		03:45:00	T52
# HIKA_B 172.29.132.31	14:15:00	B1
# 	 		14:30:00	T2
# 	 		14:45:00	T3
# 	 		15:00:00	T4
# 	 		15:15:00	T50
# 	 		15:30:00	T51
# 	 		15:45:00	T52
# AUSY_A 172.29.135.30	10:15:00	B1
# 	 		10:30:00	T2
# 	 		10:45:00	T3
# 	 		11:00:00	T4
# 	 		11:15:00	T50
# 	 		11:30:00	T51
# 	 		11:45:00	T52
# AUSY_B 172.29.135.31	20:15:00	B1
# 	 		20:30:00	T2
# 	 		20:45:00	T3
# 	 		21:00:00	T4
# 	 		21:15:00	T50
# 	 		21:30:00	T51
# 	 		21:45:00	T52
#############################################################################################################
# tems_adm/Tem$-WS
#############################################################################################################
#
# This file was generated by Pentaho Data Integration
# Look in the PDI (a.k.a. Kettle) distribution in the samples/transformations folder for a transformation called:
# 
# "Properties output - normalising data before output"
# expected folders: B1,T2,T3,T4,T50,T51,T52
# 
#Thu Jul 12 01:46:14 UTC 2018

#Pre production
db_ip=10.10.13.201
db_name=pm_db
db_port=3306
db_user=mediation_rw
db_pass=PqTLyM41TjEuiTfF

#NZHQ
ftp_server_ip=172.29.136.30
ftp_server_password=tems_adm
ftp_server_directory=/home/tems_adm/temsNMS/schedReport/new/och

#AUSY_A
#ftp_server_ip=172.29.135.30
#ftp_server_password=Tem$-WS
#ftp_server_directory=/home/tems_adm/temsNMS/schedReport/och


local_file_directory=/hawaiki_il/tesubcom/och
email_destination_address=itdev@hawaikicable.co.nz


#Test 
#db_ip=10.8.12.12
#db_name=pm_db
#db_port=3306
#db_user=root
#db_pass=admin
#ftp_server_ip=10.8.12.12
#ftp_server_directory=/home/tems_adm/temsNMS/schedReport/och
#local_file_directory=E:/sree/kettle/TEMS/tesubcom - Pre prod/och
#email_destination_address=magesh.cannane@hawaiki.co.nz
#email_destination_address=akshat.tandon@hawaiki.co.nz
#email_destination_address=sreeraj.sreenivasan@hawaiki.co.nz


ftp_server_port=21
ftp_server_username=tems_adm
ftp_logs_directory=ftp_logs/ftp_logs.txt


email_sender_address=no-reply@bw-digital.com
smtp_server=smtp.office365.com
port=587
password=JkKL7+su&=wybsLGjnY@&j5ZV^e_C^J&%LvqrdQk
#password=JkKL7+su&=wybsLGjnY@&j5ZV^e_C^J&%LvqrdQ
subject=Missing PM Sources - TEMS Pre production - 10.10.12.108

subject_q_factor=Q Factor Report - TEMS Pre production - 10.10.12.108
file_path_q_factor=/email/q_factor_report.txt

email_qfactor_address=itdev@hawaikicable.co.nz
#email_qfactor_address=sreeraj.sreenivasan@hawaiki.co.nz


