version: '3'

services:
  brokergrafana:
        image: bwdigital/brokergrafana:v1.0.0
        container_name: brokergrafana
        restart: unless-stopped
        environment:
          SPRING_PROFILES_ACTIVE: dev
        networks:
            - preprod_network
        expose:
            - "3200"
        volumes:
            - '/docker-files/brokergrafana-volume/logs:/var/logs'

networks:
    preprod_network:
        external: true
