version: '3'

services:
  brokergrafana:
    image: bwdigital/brokergrafana:v1.0.0
    container_name: brokergrafana
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - prod_network
    expose:
      - "3200"
    volumes:
      - '/docker-files/brokergrafana-volume/logs:/var/logs'

networks:
  prod_network:
    external: true
