[SERVICE]
    Flush        1
    Log_Level    info

[INPUT]
    Name        tail
    Path        /hawaiki_il/**/*.log
    Tag         pm
    DB          /fluent-bit/tail.db
    Path_Key    filepath
    Mem_Buf_Limit 50MB
    Skip_Long_Lines On

[FILTER]
    Name  rewrite_tag
    Match pm

    Rule  $filepath .*bandwidth\.log            bandwidth            true
    Rule  $filepath .*ciena_backhaul\.log       ciena_backhaul       true
    Rule  $filepath .*ciena_ettp\.log           ciena_ettp           true
    Rule  $filepath .*ciena_sttp\.log           ciena_sttp           true
    Rule  $filepath .*ciena_otu\.log            ciena_otu            true

    Rule  $filepath .*ciena_ne_c6500ettp\.log   ciena_ne_c6500ettp   true
    Rule  $filepath .*ciena_ne_c6500sttp\.log   ciena_ne_c6500sttp   true

    Rule  $filepath .*ciena_ne_ws5_ptp\.log     ciena_ne_ws5_ptp     true
    Rule  $filepath .*ciena_ne_ws5\.log         ciena_ne_ws5         true

    Rule  $filepath .*ciena_ne_ws_ptp\.log      ciena_ne_ws_ptp      true
    Rule  $filepath .*ciena_ne_ws\.log          ciena_ne_ws          true
    Rule  $filepath .*ciena_ne_wsai\.log        ciena_ne_wsai        true

    Rule  $filepath .*                          unknown              true

[OUTPUT]
    Name   loki
    Match  *
    Host   10.10.1.4
    Port   3101
    Labels job=pm,filepath=$filepath