version: '3'

services:
    cms:
        image: bwdigital/cms:v1.0.0
        container_name: cms
        restart: unless-stopped
        networks:
            - prod_network
        deploy:
            resources:
                limits:
                    memory: 2048M
        ports:
            - "9006:9006"
            - "5702:5702/udp"
        environment:
            - SPRING_PROFILES_ACTIVE=prod
        volumes:
            - '/docker-files/cms-volume/logs:/var/logs'

networks:
    prod_network:
        external: true
