#database settings
db_ip=ausy-db-mdb-oss-m2.local.hawaiki.co.nz
db_name=pm_db
db_port=3306
db_user=mediation_rw
db_pass=RKbZ4NzQJrL20tmu

#job settings
sleep_after_REST_attempt=TRUE
sleep_timer=3
duration_days=1
binstate_log=TRUE
get_data_table=ciena_backhaul_raw
insert_data_table=tems_och_old

#AUSY
alm_url=http://navigator-ncs-ausy.local.bw-digital.com/nsa/api/v2_0/alarms/filter/filteredAlarms
token_url=http://navigator-ncs-ausy.local.bw-digital.com/tron/api/v1/oauth2/tokens
pm_url=http://navigator-ncs-ausy.local.bw-digital.com/pm/api/v3/query/metrics
username=ics-radapi
password=fE8aXgHbFBba

#for NE
username_ne=ics-radmcp
password_ne=dYW76RwW3ZLg

#email 
email_destination_address=oyip@bw-digital.com itdev@bw-digital.com operations-noc@hawaikicable.co.nz
email_sender_address=no-reply@bw-digital.com
email_smtp_server=smtp.office365.com
email_port=587
email_smtp_password=JkKL7+su&=wybsLGjnY@&j5ZV^e_C^J&%LvqrdQk
email_subject=Missing PM Sources - Ciena WS Production - 10.7.2.104
