export class Card {
  constructor(
    public id?: number,
    public cardlabelname?: string,
    public site?: string,
    public cardtype?: CardType,
    public roomlocation?: string,
    public shelf?: string,
    public slot?: string,
    public position?: string,
    public connector?: string,
    public dls?: string,
    public freeports?: number,
    public totalports?: number,
    public capacity?: number,
    public wavelength?: string,
    public frequency?: string,
    public tx?: boolean,
    public vendor?: string,
    public comment?: string,
    public prrperties?: string,
    public thirdparty?: string,
    public cardcomment?: string,
    public nodename?:string
  ) {}
}

export const enum CardType {
  'WSAI' = 'WSAI',
  'MOTR' =  'MOTR',
  'FOTR' =  'FOTR',
  'TRANSP' =  'TRANSP',
  'MUXP' = 'MUXP',
  'C5160' = '5160',
  'C5170' = '5170',
  'ODF_TRX' = 'ODF_TRX',
  'ODF_MRB' = 'ODF_MRB',
  'ODF_COL' = 'ODF_COL',
  'ODF_MMR' =  'ODF_MMR',
  'ODF_DIR' = 'ODF_DIR',
  'ODF_MRH' = 'ODF_MRH'
}
export const enum PosType {
  'F' = 'F',
  'B' = 'B',
}

export const enum ConnectorType {
  'SCA' = 'SCA',
  'SCU' = 'SCU',
  'LC' = 'LC',
  'LCU' = 'LCU',
  'N/A' = 'N?A',
}

export const enum SlotType {
  'S1' = 'S1',
  'S2' = 'S2',
  'S3' = 'S3',
  'S4' = 'S4',
  'S5' = 'S5',
  'S6' = 'S6',
  'S7' = 'S7',
  'S8' = 'S8',
  'S9' = 'S9',
  'S10' = 'S10',
  'S11' = 'S11',
  'S12' = 'S12',
  'S13' = 'S13',
  'S14' = 'S14',
  'M1' = 'M1',
  'M2' = 'M2',
  'M3' = 'M3',
  'N/A' = 'N/A',
}
export const enum ShelfType {
  'A1' = 'A1',
  'A2' = 'A2',
  'A3' = 'A3',
  'A4' = 'A4',
  'A5' = 'A5',
  'RU01' = 'RU01',
  'RU02' = 'RU02',
  'RU03' = 'RU03',
  'RU04' = 'RU04',
  'RU05' = 'RU05',
  'RU06' = 'RU06',
  'RU07' = 'RU07',
  'RU08' = 'RU08',
  'RU09' = 'RU09',
  'RU10' = 'RU10',
  'RU11' = 'RU11',
  'RU12' = 'RU12',
  'RU13' = 'RU13',
  'RU14' = 'RU14',
  'RU15' = 'RU15',
  'RU16' = 'RU16',
  'RU17' = 'RU17',
  'RU18' = 'RU18',
  'RU19' = 'RU19',
  'RU20' = 'RU20',
  'RU21' = 'RU21',
  'RU22' = 'RU22',
  'RU23' = 'RU23',
  'RU24' = 'RU24',
  'RU25' = 'RU25',
  'RU26' = 'RU26',
  'RU27' = 'RU27',
  'RU28' = 'RU28',
  'RU29' = 'RU29',
  'RU30' = 'RU30',
  'RU31' = 'RU31',
  'RU32' = 'RU32',
  'RU33' = 'RU33',
  'RU34' = 'RU34',
  'RU35' = 'RU35',
  'RU36' = 'RU36',
  'RU37' = 'RU37',
  'RU38' = 'RU38',
  'RU39' = 'RU39',
  'RU40' = 'RU40',
  'RU41' = 'RU41',
  'RU42' = 'RU42',
}
