# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
  level:
    ROOT: INFO
    tech.jhipster: INFO
    org.hibernate.SQL: INFO
    com.bwd.nms: DEBUG

management:
  zipkin: # Use the "zipkin" Maven profile to have the Spring Cloud Zipkin dependencies
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
      export:
        enabled: false
  tracing:
    sampling:
      probability: 1.0 # report 100% of traces

  ticket:
    queue: NOC Incidents
    queueinternal: NOC-Internal
    defaultEmail: oyip@bw-digital.com
    defaultFrom: support@bw-digital.com
    state: open
    priority: 3
    broker: http://10.10.1.4:3000
    content: text/html; charset=utf8
    account: api
    server: https://ticketing.test.local.bw-digital.com/

spring:
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereload
  jackson:
    serialization:
      indent-output: true
  liquibase:
    # Remove 'faker' if you do not want the sample data to be loaded automatically
    contexts: dev #, faker
    url: jdbc:mariadb://10.10.13.201:3306/nms?useLegacyDatetimeCode=false
  mail:
    host: smtp.office365.com
    port: 587
    username: no-reply@bw-digital.com
    password: JkKL7+su&=wybsLGjnY@&j5ZV^e_C^J&%LvqrdQk
    protocol: smtp
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.office365.com
  messages:
    cache-duration: PT1S # 1 second, see the ISO 8601 standard
  r2dbc:
    url: r2dbc:mysql://10.10.13.201:3306/nms?useLegacyDatetimeCode=false
    username: root
    password: OKWFw0Oe8sKKXC
  thymeleaf:
    cache: false

server:
  port: 9005
  # make sure requests the proxy uri instead of the server one
  forward-headers-strategy: native

# ===================================================================
# JHipster specific properties
#
# Full reference is available at: https://www.jhipster.tech/common-application-properties/
# ===================================================================

jhipster:
  gateway:
    rate-limiting:
      enabled: false
      limit: 100000
      duration-in-seconds: 3600
  # CORS is only enabled by default with the "dev" profile
  cors:
    # Allow Ionic for JHipster by default (* no longer allowed in Spring Boot 2.4+)
    allowed-origins: 'http://localhost:8100,https://localhost:8100,http://localhost:9000,https://localhost:9000,http://localhost:4200,https://localhost:4200'
    # Enable CORS when running in GitHub Codespaces
    allowed-origin-patterns: 'https://*.githubpreview.dev'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count,X-${jhipster.clientApp.name}-alert,X-${jhipster.clientApp.name}-error,X-${jhipster.clientApp.name}-params'
    allow-credentials: true
    max-age: 1800
  security:
    authentication:
      jwt:
        # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
        base64-secret: ZGY2YWUzZGVlNjBiNjFjNGYyY2ExMmQ3YzAzNzg4MTAxNDI2ZmM0OWY2ZGU5NmU0N2YxNmUyNDdlNzg1OGM4MWIwMDc4OWIyM2UxYmFiMzQ2NGYxZmQwY2NmMDg1MGVkZDU5ODcyNzYxNDNiMmU1NWFjMzU3MTA3OTM0Yjc4MTY=
        # Token is valid 24 hours
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
  mail: # specific JHipster mail property, for standard properties see MailProperties
    from: no-reply@bw-digital.com
    base-url: http://10.10.1.4:9005
  logging:
    use-json-format: false # By default, logs are not in Json format
    logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
      enabled: false
      host: localhost
      port: 5000
      ring-buffer-size: 512


# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration, like in the JHipsterProperties above
#
# More documentation is available at:
# https://www.jhipster.tech/common-application-properties/
# ===================================================================

# application:

mediation:
  datasource:
    url: r2dbc:mysql://10.10.13.201:3306/pm_db
    username: root
    password: OKWFw0Oe8sKKXC

orientdb:
  datasource:
    url: remote:10.10.13.18/TransmissionV2
    username: root
    password: xKmMRXrqBq9wuLLb

azure:
  search:
    endpoint: https://bwd-search-serv-prod.search.windows.net
    apikey: FxssqOB1nhgUaGVN4gcJmHKS4MSvXLwiGEmjQVUr8wAzSeDpb2GN
    index-name: eng-user-manual-idx-prod
    api-version: 2021-04-30-Preview
  openai:
    endpoint: https://azure-openai-serv-prod.openai.azure.com
    apikey: Ba8FiaN4fcDBMZ3CJAJSpzhcUBfYj6TAbkngTyv25YThAxU54aSlJQQJ99BHACL93NaXJ3w3AAABACOGRThB
    deployment-name: gpt-4o
    api-version: 2024-02-15-preview
    text-embedding-name: text-embedding-3-large

mcp:
  url: http://navigator-ncs-ausy.local.bw-digital.com
  ip: http://navigator-ncs-ausy.local.bw-digital.com
  tenant: master
  username: ics-radapi
  password: fE8aXgHbFBba
  grant_type: password

otrs:
  datasource:
    url: r2dbc:mysql://10.10.13.201:3306/otrs
    username: root
    password: OKWFw0Oe8sKKXC

ticketing:
  server: https://ticketing.test.local.bw-digital.com

gateway:
  kong:
    url: http://10.10.1.4:9500
    apikey: Hardware-0-Unbolted-0-Cufflink-0-Concierge-0-Unproven-0-Uneasy-0-Wham-0-Visibly

