
#AUZY_A
ftp_server_ip=172.29.135.30
ftp_server_port=21
ftp_server_username=tems_adm
ftp_server_password=Tem$-WS
ftp_server_directory=/home/tems_adm/temsNMS/schedReport/new/pfe/pfe

local_directory=/hawaiki_il/tems-pfe/pfe

#Production DB
db_server_ip=ausy-db-mdb-oss-m2.local.hawaiki.co.nz
db_server_port=3306
db_database_name=pm_db
db_username=mediation_rw
db_password=RKbZ4NzQJrL20tmu
